### PR TITLE
Removes special handling of Hangprinter's D-anchor

### PR DESCRIPTION
**Pull request by tobbelobb**
There's nothing special about the D-anchor.

Allowing it to have non-zero xy-locations is very useful,
especially when auto-calibrating the anchor locations with help
of computer vision.

Code also gets easier to maintain, with less implicit knowledge
about Hangprinters needed.

The cost of this niceness is that the binary gets 164 bytes bigger.

I will place the line buildup compensation commit on top of this one, in the hope that 164 bytes is a manageable cost.

### CODE REVIEW

**Comment by dc42** [comment]
In that case, let's change it to have an "anchors" array instead of separate anchorA, anchorB etc.

**Comment by tobbelobb** [comment]
I'll make such an anchors array

**Comment by tobbelobb** [comment]
The buildup compensation has added another 2376 bytes

**Comment by dc42** [comment]
They can all use a common coordinates array too.

**Comment by tobbelobb** [comment]
Yup, just what I was thinking.

It would make sense (look prettier) to have an array of arrays, but I'm not entirely sure how to build the ObjectModelArrayDescriptor object in that case. I see some functions in the ObjectExplorationContext class that mention depth, but no way to pass in two indices.

Should I just make the anchors array one-dimensional? It will only be used inside HangprinterKinematics.cpp anyways.

**Comment by dc42** [comment]
You can use a 2D array. The value returned by the first array descriptor will be the descriptor for the contained array. the value returned by that array descriptor can call contect.GetlastIndex to retrieve the innermost array index, and context.GetInded(1) to return the index into the outer array i.e. the anchor number.

**Comment by dc42** [comment]
btw we are about to freeze 3,3RC1, so not much time left to accept PRs for 3.3

**Comment by tobbelobb** [comment]
Ok, I'll try the 2D way.

Does that mean I need to hurry, or point PRs to another branch?

**Comment by dc42** [comment]
It means I will need to freeze your contributions to 3.3 shortly. After that I will create a 3.4 branch.

**Comment by tobbelobb** [comment]
Ok, thanks for the heads up

**Comment by dc42** [comment]
However, i think it would be good to get the object model changes into 3.3 if we can.

**Comment by dc42** [comment]
Maybe it's best if I accept your PR for making D not special, then make the object model changes myself; then you test them? We need to finalise this soon because if there are any changes to the ON, then DSF and DWC need to be updated.

**Comment by tobbelobb** [comment]
There's something about the object model table that I need to understand as well.
I'm getting 
```
error: static assertion failed: Mismatched object model table and descriptor
```


```
constexpr ObjectModelArrayDescriptor HangprinterKinematics::anchorsArrayDescriptor =
{
	nullptr,					// no lock needed
	[] (const ObjectModel *self, const ObjectExplorationContext&) noexcept -> size_t { return HANGPRINTER_AXES*3; },
	[] (const ObjectModel *self, ObjectExplorationContext& context) noexcept -> ExpressionValue { return ExpressionValue(((const HangprinterKinematics *)self)->anchors[context.GetIndex(1)][context.GetLastIndex()], 3); }
};

constexpr ObjectModelTableEntry HangprinterKinematics::objectModelTable[] =
{
	// Within each group, these entries must be in alphabetical order
	// 0. kinematics members
	{ "anchors",	OBJECT_MODEL_FUNC_NOSELF(&anchorsArrayDescriptor), 	ObjectModelEntryFlags::none },
	{ "name",		OBJECT_MODEL_FUNC(self->GetName(true)), 			ObjectModelEntryFlags::none },
	{ "printRadius",	OBJECT_MODEL_FUNC(self->printRadius, 1), 		ObjectModelEntryFlags::none },
};

```

**Comment by tobbelobb** [comment]
Sure!

**Comment by dc42** [comment]
You've replaced 4 anchor variables by 1 so there are onw just 3. so this line:
`constexpr uint8_t HangprinterKinematics::objectModelTableDescriptor[] = { 1, 6 };`
should now be:
`constexpr uint8_t HangprinterKinematics::objectModelTableDescriptor[] = { 1, 3 };`

**Comment by tobbelobb** [comment]
It works =D Saves 420 bytes. Pushing...

**Comment by tobbelobb** [comment]
Ended up at 1964 bytes for non-special D + buildup compensation.

This has not been tested on hw, and probably won't for a few days. It is however a copy/paste of code that has been running a lot.

I'm ok with merging it untested, to reduce the number of branches we need to keep track of, and since I will continue to work on this for a while anyways. But I'm fine with rebasing onto 3.4-dev later also, and making a new PR when I have tested on hw.

**Comment by tobbelobb** [comment]
From reading my own comment, I realize I should set up a hw testing rig first thing tomorrow.

Have a nice evening!

**Comment by dc42** [comment]
Thanks for your contribution. I have made and pushed a correction to the object model tables.

**Pull request merged**
