### PR TITLE
Implement flashing PanelDue v3 from Duet mainboards

### PR DESCRIPTION
**Pull request by wilriker**
This uses the required code extracted from BOSSA

### CODE REVIEW

**Review by dc42 — COMMENTED** [review]
Looks good, just a few comments:
1. In PanelDueUpdater::Spin, the exception handling is the same for each case that has a try-block. I suggest you put the try..catch around the switch statement instead, then you won't need the HandleException method, just a single catch block.
2. To save memory under normal use, I suggest you don't create the PanelDueUpdater object until the user actually wants to update the PanelDue firmware. Then you will need to avoid spinning it if the pointer is null.
3. Please remove the "if 0" code blocks in Bossa that we are never likely to need, e.g. the exception classes that you have replaced.

**Comment by wilriker** [comment]
I implemented the requested changes and merges `v3.02-dev`.

**Comment by wilriker** [comment]
Thanks for merging!

**Comment by joaobarros** [comment]
Thank you, this is really great!!!

I'll update the wiki with the necessary command and filename but here's 2 suggestions:

1)Verify the bin file exists before erasing the PanelDue?

02/12/2020, 14:58:24 | M997 S4 Sending Erase-and-Reset command to PanelDue
02/12/2020, 14:58:25 | Establishing connection to PanelDue bootloader
02/12/2020, 14:58:25 | Unlocking PanelDue flash memory Erasing PanelDue flash memory
02/12/2020, 14:58:27 | Error: Failed to open file 0:/sys/PanelDueFirmware.bin Error: Flashing PanelDue failed in step bossaWrite. Please try again.

After uploading the file *without* resetting the PanelDue I was able to upgrade it but the restart did not occur, I had to do it manually:
02/12/2020, 15:00:28 | Restarting PanelDue

I'm going to test with another PanelDue on another printer with the correct steps in place, like having the .bin uploaded :)

2) As with other firmware files, recognize the file and prompt the user to upgrade firmware without the need for the manual M997 S4 command?

**Comment by wilriker** [comment]
The wiki has already been updated and DWC should support auto-renaming as well as asking to update with the next release.

**Pull request merged**
