### PR TITLE
ST7565 display driver many optimizations

### PR DESCRIPTION
**Pull request by SchmartMaker**
- Working simplified Flush
- Fixed a ST7920-specific assumption in drawing code.
- Made display type 2 (using EXP_1 as CS)
- Made display type 3 (needs external component to invert LCD_CS).
- Both display types 2 and 3 have EXP_0 as A0/DC line.
- Various code optimizations.

### CODE REVIEW

**Comment by SchmartMaker** [comment]
@dc42 , I understand and agree. It was an enjoyable personal exercise to see my approach working for my Maestro, but most important is RRF 3 having working ST7565 support, in line with your ideas about the structure and compatible with the various hardware platforms. I think you are the best judge of that. I sure wouldn't mind resolving the current merge conflicts and the cooperative aspects of option 2, but I think option 3 unburdens you the most, and that's what I would prefer.

**Comment by dc42** [comment]
Thanks, I'll start work on the refactoring tomorrow. I need to get the 7565 display code working on Duet 3 Mini by the end of this week. L

**Comment by dc42** [comment]
I've completed the refactoring and tested that a ST7920-based display attached to a Maestro still works. The additional code for the ST7567 should need to be mostly (or with luck, entirely) in file ST7567.cpp

**Comment by dc42** [comment]
PS - as I have very little time to get this working, I've just started putting your code in file LCD7567.cpp.

**Comment by SchmartMaker** [comment]
I pushed a Lcd7565 branch in my fork with the changes, and fixed a bug in
ClearToMargin() due to a ST7920 specific assumption. I performed a quick
test last night, but have not got it working yet.

**Comment by dc42** [comment]
Thanks, I already did a little more refactoring to make the Lcd7567 class a little more like your original, and I've now merged your version of FlushSome into it. I will test it shortly.

**Comment by SchmartMaker** [comment]
Okay, cool! About the code not working yet in my case, I think I might have
forgotten to set the LcdCSPin specifically for the Duet 2 Maestro which
gates the CLK etc.
The code might in fact work for a board that supports active low CS
natively (Maestro 3 Mini?).
So I think I'm close to getting this to work, but first going to eat
something...

**Comment by dc42** [comment]
I'm in a meeting so can't do any testing right now, but I've just committed my latest changes.

**Comment by SchmartMaker** [comment]
I have the left half of the display working on my Maestro. Trying to
pinpoint where the bug is coming from... Note that your code looks a lot
like mine, but I made it so I can test on the Maestro and corrected some
bugs e.g. TILE_WIDTH = 1.

**Comment by dc42** [comment]
Thanks. I didn't have your change to ClearToMargin yet. I've just added that but not committed it yet.

**Comment by dc42** [comment]
I've made a few more commits, including your change to ClearToMargin. The ST7920 12864 display is still working on the Maestro, but I'm getting nothing on the ST7567 Mini display on the Duet 3 Mini except the backlight. This is prototype hardware, so it could be a hardware problem. But please let me know if you see anything wrong with my ST7567 code.

**Comment by dc42** [comment]
PS - did you correct any other bugs in my code?

**Comment by SchmartMaker** [comment]
I'm not using your branch; the Lcd7565 branch is based on what you provided as a structure yesterday, which I amended with my code, and I have partial success with that. The left half of the screen is working. I think in the ST7565 branch I must have fixed some other bugs as well, because that branch is working flawlessly and I've been using that for months. I could (will) try to fix the Lcd7565 branch, but currently, at least for my build, the Lcd7565 branch results in a larger firmware binary than the ST7565 branch. Is that also your observation?

**Comment by dc42** [comment]
I haven't tried building your branch; but it appears to have more code duplication in the display driver code than mine. Perhaps the extra code size of mine is due to other improvements in RRF 3.2?

**Comment by SchmartMaker** [comment]
I was comparing the sizes of the build of the old ST7565 branch with the new Lcd7565 branch, so that didn't incorporate the changes you made since in dev-3.02. But I've now done a merge of the dev-3.02 branch of a few hours ago into the branch ST7565 (the branch with the pull request that had become out of date) so it should be more up to date and had to refactor some things because of the new SPI object, restructured the folders a bit, and when compiled it's now 502,564 bytes. So this is with all the RRF 3.2 changes.

**Comment by SchmartMaker** [comment]
The build of the Lcd7565 branch is 502,208 bytes, but that's not working and that should indeed include the RRF 3.2 changes. So my code adds 356 bytes indeed. But that code works ;)

**Comment by dc42** [comment]
Please clarify: "but that's not working" ... "But that code works" ??

**Comment by SchmartMaker** [comment]
Not working: the right half of the display was garbled, and looked compressed in the width. But I've found the problem, in the boilerplate you provided width and height were reversed for the Lcd() base class call. So I have the structure you provided fully working now and will push this to the Lcd7567 branch of my fork momentarily.

One thing remaining; I noticed that my original code performed better after a firmware upgrade, where the display showed the contents right after the "Upgrading firmware" message. The Lcd7567 code doesn't seem to do that, so maybe timings are off because the code has become faster with the new SPI classes or something like that.

**Comment by SchmartMaker** [comment]
I've pushed the branch. So, after a firmware update I manually send a "M918 P2 E4 F2000000" to the printer which fixes the blank display. Powering on the printer shows content right away (not a blank display). My old code did not do that, so that's something to investigate maybe with my logic analyzer tomorrow. I've not looked carefully at the differences between a ST7565 and a ST7567 by the way, but I wouldn't expect serious differences. The ST7920 is a completely different beast however.

**Comment by SchmartMaker** [comment]
So to be clear, if your beta hardware allows active low CS without blocking the CLK and MOSI, and the display is compatible with an ST7565, and you've connected the A0 pin, then the code now in the Lcd7567 branch should work.

**Comment by dc42** [comment]
Thanks! I've made and committed several fixes to the ST7567 cod in v3.02-dev, including the SPI mode which was incorrectly set to 0 (should have been 3). However, I still can't get my display to show anything. I added some delays to the SPI code because it wasn't allowing any sime between CS going low and the clock starting; or between the last clock pulse and CS going high. it would be helpful if you can check whether this code works with your display.

**Comment by dc42** [comment]
I got it working. The main issue turned out to be that the display initialisation settings were wrong for the display I used (Fysetc Mini 12864) so there was almost no contrast. Thanks for all your help!

**Comment by SchmartMaker** [comment]
I'm so glad to hear you've got it working! I vaguely remember some displays have issues with software contrast control and need the maximum value, some have hardware control in the form of a small potentiometer. Tomorrow I'll check if my display still works with your updated branch.  Sorry I wasn't able to do this sooner, I had some other stuff going on...

**Comment by SchmartMaker** [comment]
Hi, I just checked your branch, but I now have a blank display on a Duet 2 Maestro, since the code to use an alternative pin for chip select (and setting the actual CS pin high to allow CLK and MOSI to pass through) is missing.

In my old more generic branch I just defined two additional display types, one display type with an alternative CS pin and one without (the latter probably is suitable for the Duet 3 Mini). Do you have any suggestions how to elegantly solve this for both the Maestro and the Mini? One of the reasons my code was so generic is to be able to easily handle I2C displays, UART and parallel displays in the future, and cases like above, including displays needing different SPI modes.

- I also see some left-overs from the more efficient (but slightly bigger) flush code with the TransformTile method.
- I noticed you removed the part where the ST7565 enters powersaving mode briefly, I guess that's totally fine.

**Comment by SchmartMaker** [comment]
I guess what I'm asking is not to leave us Maestro users in the dark. I.e. with a dark display :smile:

**Comment by dc42** [comment]
Can you suggest the minimum changes needed to get my current code working with the Maestro? I suggest we use fixed GPIO pin assignments for CS and A0. It will also be necessary to set the "old" CS pin high so that the clock gets through.

**Comment by SchmartMaker** [comment]
The necessary adjustments were already present in the Lcd7567 branch in my fork, in the Lcd7567.cpp and Lcd.cpp files, after the "#ifdef SRC_DUETM_PINS_DUETM_H_" statement and in Pins_DuetM.h marked with "constexpr Pin LcdAltCSPin = PortAPin(22);". The ifdef method I used may not be the designated way to detect a Maestro build, but I had to use something to make sure that the firmware remained compatible with other hardware platforms and to not impact the existing ST7920 display support.

I actually much prefer the way I did it in Display.cpp in the ST7565 branch of my fork, where I used different display ID's to differentiate between display configurations, but as you mentioned, that code is slightly more elaborate and might not fit the older Duet 2 boards.

So the solution in the Lcd7567 branch may be more 'hacky' but it does take less space.

>

**Comment by SchmartMaker** [comment]
> Can you suggest the minimum changes needed to get my current code working with the Maestro? I suggest we use fixed GPIO pin assignments for CS and A0. It will also be necessary to set the "old" CS pin high so that the clock gets through.

Hi @dc42, David, I had some time this afternoon to suggest some changes through example. This is in [my fork](https://github.com/SchmartMaker/RepRapFirmware/tree/v3.02-dev/src/Display) of RepRapFirmware, and based on the latest v3.02-dev branch, so it'll be easy to merge if needed. Obviously, I didn't test for a different board since I only own one. I did my best to keep the structure and spirit of your code, make it as maintainable as possible and at the same time not too specific for my case only.

Some observations:

- After firmware update, the display resets nicely now, no second M918 command is needed anymore to nudge my display to life.
- Multiple M918 commands (like 5 or 6 instances) sent through DWC after each other will reset my Maestro board.
- Do you need to set the resistor ratio for your ST7567 to 0x06, or can it be 0x03 as I used before?
- The contrast for my display was way to dark, so I had to incorporate an experimental contrast parameter which made the content on my display visible again.

**Comment by dc42** [comment]
Hi, are you able to implement your changes for Duet Maestro support as a PR to the latest v3.02-dev branch again? I have already defined LcdA0Pin as pin PA21 in Pins_DuetM.h. I'd like to leave the default resistor ratio as 0x06, because it works for my display and it is the value that other drivers use, but I agree that a contrast parameter is needed.

**Comment by mschiedon** [comment]
> Hi, are you able to implement your changes for Duet Maestro support as a PR to the latest v3.02-dev branch again?

Yes, no problem. I'll probably be able to make some time for this tonight; I'll resolve any conflicts, test a firmware build locally and will create a new PR for that (so we can close this obsolete one).

P.S. I don't validate the contrast parameter value yet, and this may be something I need help with to make the option production ready.

**Comment by dc42** [comment]
Superseded by #424.

**Pull request closed without merging**
