### PR TITLE
Re-implementation of ST7567 support for Duet 2 Maestro on v3.02

### PR DESCRIPTION
**Pull request by SchmartMaker**
Hi David, as discussed in [issue 408](https://github.com/Duet3D/RepRapFirmware/pull/408) a new pull request for the re-implemented ST7567 changes for the Duet 2 Maestro, against the v3.02-dev branch.

### CODE REVIEW

**Comment by dc42** [comment]
Thanks for your PR.
1. Is it really necessary to toggle the gate pin every time we select the ST7567? Can't we just set it high during initialisation and leave it there? The ST7567 doesn't mind seeing clock signals when its CS line is high.
2. Please revert your change to .gitignore. Folder DuetM_RTOS has been replaced by DuetMaestro.

**Comment by SchmartMaker** [comment]
> 1. Is it really necessary to toggle the gate pin every time we select the ST7567? Can't we just set it high during initialisation and leave it there? The ST7567 doesn't mind seeing clock signals when its CS line is high.

Thanks for noticing! I don't see any harm in setting this pin high permanently, since the LCD_CS is exclusively for the display. I've made that change and tested, and everything still worked on my end.

> 2. Please revert your change to .gitignore. Folder DuetM_RTOS has been replaced by DuetMaestro.

Did this as well, and now also removed local folder DuetM_RTOS which caused a lot of unstaged changes to appear.

**Comment by dc42** [comment]
I've merged your changes, but simplified the gate pin control a little because it only applies to the Duet Maestro so IMO it doesn't really belong in the Display class. I did some research and found that several types of display use a resistor ratio of 3 like yours, so I've added a R parameter to the M918 command to configure that. Are you able to test my changes before I release RRF 3.2beta2? I can supply a ready-built binary it it helps.

**Comment by SchmartMaker** [comment]
> I've merged your changes, but simplified the gate pin control a little because it only applies to the Duet Maestro so IMO it doesn't really belong in the Display class. I did some research and found that several types of display use a resistor ratio of 3 like yours, so I've added a R parameter to the M918 command to configure that. Are you able to test my changes before I release RRF 3.2beta2? I can supply a ready-built binary it it helps.

Hi David, thank you for implementing the resistor ratio setting! It provides a much more granular control over the contrast on my display, so this is great! Apart from the firmware crashing when you issue M918 five or six times in a row (this is a plausible user scenario where you try to find out which contrast setting works best), everything still works fine on my own build. However, for added validation , please send me your pre-built binary as well and I will also test that on my machine.

**Comment by dc42** [comment]
I've fixed the  memory leak when you run M918 multiple times, and put a new binary for the Maestro at https://www.dropbox.com/s/raauoua2mu0ge1b/DuetMaestroFirmware.bin?dl=0.

**Pull request merged**
